services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

  api:
    image: golang:1.25-alpine
    working_dir: /app
    volumes:
      - .:/app
      - go_mod_cache:/root/go/pkg/mod
    ports:
      - "8080:8080"
    command: sh -c "go install github.com/air-verse/air@latest && air"
    env_file: .env.local
    environment:
      - REDIS_URL=redis:6379
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started


volumes:
  postgres_dev_data:
  redis_dev_data:
  go_mod_cache: